# Avalon config
# Eklenti blestit tarafından yazılmıştır. Provanas Skyblock Avalon harici bir bölümde/sunucuda kullanılması yasaktır.
#
# Eklentinin güncel versiyonu eklendiyse bu dosyayı silip oyun içi reload atınız.
# Aksi takdirde yeni özellikler çalışmayacaktır.
# Eğer lore a "§b§lDEBUG MODE" eklerseniz vurduğunuz hasarı sadece sizin görebileceğiniz bir mesaj şeklinde gönderir.
# !!!DİKKAT!!!  ->  & işareti bozuyor. Onun yerine § kullanın.
nerfphantom:
  nerfrate: 90
  #100 -> no phantom
  #0 -> no nerf

dragon:
  altarlar:
    - "-10 73 18"
    - "-12 73 16"
    - "-12 73 -6"
    - "-10 73 -8"
    - "12 73 -8"
    - "14 73 -6"
    - "14 73 16"
    - "12 73 18"
  dragonloc:
    x: 1
    y: 85
    z: 5

dragons:
  koruyucu:
    Display_name: "§5§lKoruyucu Ejderha"
    Health: 9000000
    Damage: 100.0
    Speed: 1.0
    Armor: 0
    SkillDamage: 200
    SkillCooldown: 1200
    Chance: 16
  yasli:
    Display_name: "§5§lYaşlı Ejderha"
    Health: 15000000
    Damage: 100.0
    Speed: 1.0
    Armor: 0
    SkillDamage: 200
    SkillCooldown: 1200
    Chance: 16
  genc:
    Display_name: "§5§lGenç Ejderha"
    Health: 7500000
    Damage: 100.0
    Speed: 1.5
    Armor: 0
    SkillDamage: 200
    SkillCooldown: 1200
    Chance: 16
  bilge:
    Display_name: "§5§lBilge Ejderha"
    Health: 9000000
    Damage: 100.0
    Speed: 1.5
    Armor: 0
    SkillDamage: 200
    SkillCooldown: 900
    Chance: 16
  guvenilmez:
    Display_name: "§5§lGüvenilmez Ejderha"
    Health: 9000000
    Damage: 100.0
    Speed: 1.5
    Armor: 0
    SkillDamage: 350
    SkillCooldown: 1200
    Chance: 16
  guclu:
    Display_name: "§5§lGüçlü Ejderha"
    Health: 9000000
    Damage: 150.0
    Speed: 1.5
    Armor: 0
    SkillDamage: 200
    SkillCooldown: 1200
    Chance: 16
  kilgharrah:
    Display_name: "§6§lKilgharrah Ejderhası"
    Health: 12000000
    Damage: 200.0
    Speed: 1.2
    Armor: 0
    SkillDamage: 350
    SkillCooldown: 1000
    Chance: 2
  kutsal:
    Display_name: "§6§lKutsal Ejderha"
    Health: 17500000
    Damage: 150.0
    Speed: 1.0
    Armor: 0
    SkillDamage: 200
    SkillCooldown: 700
    Chance: 2




PlayerPing:
  Sound: "ENTITY_ARROW_HIT_PLAYER"
    #Oyuncu pinglendiğinde çıkan ses. Default: ENTITY_ARROW_HIT_PLAYER
  #ping permi avalon.ping

blazecancel:
  world: "bskyblock_world"
#Buraya hangi world u yazarsanız ordaki blazelerin ateş etmesini engeller. Default: bskyblock_world

grapplinghook:
  prefix: "§7[§6Avalon§7] "
  #& işareti bozuyor. Onun yerine § kullanın. Aranan display_name: §5Kanca
  cooldowntext: "§4Eşya özelliği hazır değil!"
  #Cooldown mesajını ayarlar. Default: "§4Eşya özelliği hazır değil!"
  nopermtext: "§eBunu kullanabilmeniz için Soylu olmanız lazım"
  #perm yoksa ve kanca kullanmaya çalışırsanız bu mesaj gönderilecek. Default: "§eBunu kullanabilmeniz için Soylu olmanız lazım"
  #perm: use.hook
  velocity:
    air:
      #Kancayı havada çekerseniz bu ayar tetiklenir.
      onairvelocity: 3
      #Havada gitme hızını ayarlar. Default: 3
      onairsety: 1
      #Havada y ekseninde gitme hızını ayarlar. Default: 1
    land:
      #Kancayı karada çekerseniz bu ayar tetiklenir.
      onlandvelocity: 0.4
      #Karada gitme hızını ayarlar. Bu kısım kesirli olmalıdır. Default: 0.4
      onlandchangeadd:
        #Karada gideceği son noktayı değiştirir.Y kısmı kesirli diğerleri tam sayı olmalıdır. Default: x: 0 , y: 2.6 , z: 0
        x: 0
        y: 2.6
        z: 0



saklambactool:
  item:
    need_lore: "§4§lETKINLIK ESYASI"
    #Eğer elinizde tuttuğunuz herhangi bir eşyanın lore unda bu geçiyorsa saklambaç eşyası olarak çalışacaktır. Default: §4§lETKINLIK ESYASI
    #Farklı bir pluginden eşyayı üretip lore una bunu koyabilirsiniz.
    ebe_effect: "GLOWING"
    #Eğer bu efekt oyuncuda varsa onu ebe olarak algılar ve onu ebeleyemez. Default: GLOWING
    command: "spawn"
    #Ebelenen kişiye yazdırılan komuttur. Default: spawn
  text:
    prefix: "§7[§6Avalon§7] "
    #& işareti bozuyor. Onun yerine § kullanın.
    ebelendin: "§e§lEbelendin!"
    #Ebelendin yazısını düzenler.
    ebeledin: "§e§lBir oyuncuyu ebeledin!"
    #ebeledin yazısını düzenler.
    ebeyiebeleyemezsin: "§c§lBir ebeyi ebeleyemezsin!"
    #ebeyiebeleyemezsin yazısını düzenler
    cooldown_text: "§4Eşya özelliği hazır değil!"
    #cooldown mesajını düzenler.
    msg_color: " §e"
    #broadcast mesaj rengini düzenler.
    broadcast_text: "adlı kişiyi ebeledi."
    #broadcast mesajını düzenler. mesaj yazılma sırası: prefix + msgcolor + ebeleyenadı + ebelenen adı + broadcast_text
  effect:
    particle: "FIREWORKS_SPARK"
    #Default: FIREWORKS_SPARK
    particlepower: 150
    #Particle gücünü ayarlar. Default: 150
    sound: "ENTITY_DRAGON_FIREBALL_EXPLODE"
    #Default: ENTITY_FIREWORK_ROCKET_TWINKLE


mesaj: '&eÖldüğünüz için paranızın &6%%percent% (%money%$)''ı &egitti. Bir dahakine daha dikkatli ol!'
mesaj2: '&eRütbenizden dolayı paranız gitmedi.'

firstjoinmessages:
  messages:
    - "§7[§6Avalon§7] &6Büyük oyuncu &a%player%&6 bölüme ilk girişini yaptı! &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &a%player%&6, bölüme kayarak girdi. &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6Bir &a%player%,&6 belirdi. &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &a%player%&6 paraşütle bölüme iniş yaptı. &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6Hoşgeldin, &a%player%&6. Umarım pizza getirmişsindir. &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6Hoşgeldin, &a%player%&6. Seni bekliyorduk (^-^). &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &a%player%&6 bölüme giriş yaptı. Seems OP - please nerf. &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6&a%player%,&6 nerede? Sunucuda! &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6O bir kuş! O bir uçak! Hayır, o sadece bir &a%player%&6. &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &a%player% &6geldi, şimdi siz düşünün! &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &bZeus&6, &a%player% &6için şimşeklerini çakıyor! &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6Biz de gelene hoş geldin demek adettir. Hoş geldin &a%player%&6! &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6Yeni &3Lord&6 adayını selamlayın! İşte &a%player%&6! &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6İlk &3Kral&6 adayına hoşgeldin diyin. Selamlar &a%player%&6! &cOyuncu Sırası: #%playersize%"


sumobslist:
  - "Deniz İmparatoru"
  - "Suda Yürüyen"
  - "Kum Canavarı"
  - "Kil Canavarı"
  - "Su Gardiyanı"
  - "Su Cadısı"
  - "Su Okçusu"
  - "Derin Katil"
  - "Su Kedisi"
  - "Havuç Kral"
  - "Gümüş Balığı"
  - "Deniz Golemi"
  - "Su Kralı"
  - "Yeti"
  - "Buz Kurdu"
  - "Mürekkep Balığı"
  - "Donmuş Zombi"

runner:
  pistons:
    - "1191 38 -898"
    - "1190 38 -898"
    - "1189 38 -898"
    - "1188 38 -898"
    - "1187 38 -898"
    - "1186 38 -898"
    - "1185 38 -898"
    - "1184 38 -898"
    - "1183 38 -898"
    - "1182 38 -898"
    - "1181 38 -898"
    - "1180 38 -898"
    - "1179 38 -898"
    - "1178 38 -898"
skillxp:
  mining:
    - NETHERRACK:0.5
    - GRAVEL:0.5
    - FLINT:0.5
    - ICE:0.5
    - PACKED_ICE:4.5
    - COBBLESTONE:1
    - SAND:3
    - RED_SAND:3
    - END_STONE:3
    - QUARTZ:3
    - QUARTZ_BLOCK:12
    - COAL:5
    - COAL_BLOCK:45
    - GLOWSTONE:7
    - GLOWSTONE_DUST:1.75
    - COAL:3
    - IRON_INGOT:5
    - IRON_BLOCK:45
    - COPPER_INGOT:5
    - COPPER_BLOCK:45
    - GOLD_INGOT:6
    - GOLD_BLOCK:54
    - LAPIS_LAZULI:7
    - LAPIS_BLOCK:63
    - REDSTONE:7
    - REDSTONE_BLOCK:63
    - EMERALD:9
    - EMERALD_BLOCK:81
    - DIAMOND:10
    - DIAMOND_BLOCK:90
    - OBSIDIAN:20
  combat:
    - STRING:2
    - SPIDER_EYE:3
    - ROTTEN_FLESH:3
    - BONE:2
    - BLAZE_ROD:3
    - GHAST_TEAR:5
    - GUN_POWDER:3
    - SLIME_BALL:2
    - MAGMA_CREAM:2
    - ENDER_PEARL:3
  woodcutting:
    - OAK_LOG:6
    - BIRCH_LOG:6
    - SPRUCE_LOG:6
    - JUNGLE_LOG:6
    - ACACIA_LOG:6
    - DARK_OAK_LOG:6
    - CRIMSON_STEM:14
    - WARPED_STEM:14
  farming:
    - BAMBOO:1
    - SWEET_BERRIES:3
    - GLOW_BERRIES:3
    - CACTUS:2
    - GREEN_DYE:2
    - SUGAR_CANE:2
    - NETHER_WART:4
    - COCOA_BEANS:4
    - WHEAT:4
    - HAY_BLOCK:36
    - BEETROOT:5
    - CARROT:4
    - POTATO:4
    - MELON_SLICE:0.4
    - MELON:4
    - PUMPKIN:4.5
    - RED_MUSHROOM:6
    - BROWN_MUSHROOM:6
  fishing:
    - COD:25
    - SALMON:35
    - PUFFERFISH:50
    - TROPICAL_FISH:100
    - CLAY_BALL:30
    - CLAY:120
  alchemy:
    - NETHER_WART:0.5
  zindan:
    - NETHERITE_INGOT:25
    - NETHERITE_BLOCK:225

projectiledamagefix:
  1:
    namestartswith: "§8[§cLv15§8] §cBlaze "
    damage: 1000
  2:
    namestartswith: "§8[§cLv45§8] §cBlaze "
    damage: 10000

blazeboss:
  namestartswith: "§8[§cLv45§8] §cBlaze "
  #This message will be sent to the players who damaged the blaze boss.
  rewardmessage: |
    &c▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
    &6               Blaze Mağlup Edildi
    &f
    &c&l       1. %top_name_1%: %top_damage_1%
    &6&l       2. %top_name_2%: %top_damage_2%
    &e&l       3. %top_name_3%: %top_damage_3%
    &f
    &b      Hasarın: %personal_damage%
    &f
    &c▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
  RewardCommands:
    #reward commands. If you set "none" it won't reward. You can increase or decrease the number of rewards to be given to different people.
    all:
      - "give %player% coal %10"
    #participation reward / reward everyone who deals damage
    1:
      - "give %player% apple 1 %20"
      - "give %player% diamond 1"
      - "give %player% gold_ingot 1"
    #reward for most damager
    2:
      - "give %player% emerald 1"
    #reward for secondnd person who inflicted the most damage
    3:
      - "give %player% iron_ingot 1"
    #reward for thirrd person who inflicted the most damage
    4:
      - "give %player% iron_ingot 1"
    #reward for fourth person who inflicted the most damage
    5:
      - "give %player% iron_ingot 1"
    #reward for fifth person who inflicted the most damage
    6:
      - "give %player% iron_ingot 1"
    #reward for sixth person who inflicted the most damage
    7:
      - "give %player% iron_ingot 1"
    #reward for seventh person who inflicted the most damage
    8:
      - "none"
    #reward for eight person who inflicted the most damage
    9:
      - "none"
    #reward for ninth person who inflicted the most damage
    10:
      - "none"
    #reward for tenth person who inflicted the most damage