# Avalon config
# Eklenti blestit tarafından yazılmıştır. Provanas Skyblock Avalon harici bir bölümde/sunucuda kullanılması yasaktır.
#
# Eklentinin güncel versiyonu eklendiyse bu dosyayı silip oyun içi reload atınız.
# Aksi takdirde yeni özellikler çalışmayacaktır.
# Eğer lore a "§b§lDEBUG MODE" eklerseniz vurduğunuz hasarı sadece sizin görebileceğiniz bir mesaj şeklinde gönderir.
# !!!DİKKAT!!!  ->  & işareti bozuyor. Onun yerine § kullanın.
nerfphantom:
  nerfrate: 90
  #100 -> no phantom
  #0 -> no nerf

dragon:
  altarlar:
    - "-10 73 18"
    - "-12 73 16"
    - "-12 73 -6"
    - "-10 73 -8"
    - "12 73 -8"
    - "14 73 -6"
    - "14 73 16"
    - "12 73 18"
  dragonloc:
    x: 1
    y: 85
    z: 5


PlayerPing:
  Sound: "ENTITY_ARROW_HIT_PLAYER"
    #Oyuncu pinglendiğinde çıkan ses. Default: ENTITY_ARROW_HIT_PLAYER
  #ping permi avalon.ping

blazecancel:
  world: "bskyblock_world"
#Buraya hangi world u yazarsanız ordaki blazelerin ateş etmesini engeller. Default: bskyblock_world

grapplinghook:
  prefix: "§7[§6Avalon§7] "
  #& işareti bozuyor. Onun yerine § kullanın. Aranan display_name: §5Kanca
  cooldowntext: "§4Eşya özelliği hazır değil!"
  #Cooldown mesajını ayarlar. Default: "§4Eşya özelliği hazır değil!"
  nopermtext: "§eBunu kullanabilmeniz için Soylu olmanız lazım"
  #perm yoksa ve kanca kullanmaya çalışırsanız bu mesaj gönderilecek. Default: "§eBunu kullanabilmeniz için Soylu olmanız lazım"
  #perm: use.hook
  velocity:
    air:
      #Kancayı havada çekerseniz bu ayar tetiklenir.
      onairvelocity: 3
      #Havada gitme hızını ayarlar. Default: 3
      onairsety: 1
      #Havada y ekseninde gitme hızını ayarlar. Default: 1
    land:
      #Kancayı karada çekerseniz bu ayar tetiklenir.
      onlandvelocity: 0.4
      #Karada gitme hızını ayarlar. Bu kısım kesirli olmalıdır. Default: 0.4
      onlandchangeadd:
        #Karada gideceği son noktayı değiştirir.Y kısmı kesirli diğerleri tam sayı olmalıdır. Default: x: 0 , y: 2.6 , z: 0
        x: 0
        y: 2.6
        z: 0



saklambactool:
  item:
    need_lore: "§4§lETKINLIK ESYASI"
    #Eğer elinizde tuttuğunuz herhangi bir eşyanın lore unda bu geçiyorsa saklambaç eşyası olarak çalışacaktır. Default: §4§lETKINLIK ESYASI
    #Farklı bir pluginden eşyayı üretip lore una bunu koyabilirsiniz.
    ebe_effect: "GLOWING"
    #Eğer bu efekt oyuncuda varsa onu ebe olarak algılar ve onu ebeleyemez. Default: GLOWING
    command: "spawn"
    #Ebelenen kişiye yazdırılan komuttur. Default: spawn
  text:
    prefix: "§7[§6Avalon§7] "
    #& işareti bozuyor. Onun yerine § kullanın.
    ebelendin: "§e§lEbelendin!"
    #Ebelendin yazısını düzenler.
    ebeledin: "§e§lBir oyuncuyu ebeledin!"
    #ebeledin yazısını düzenler.
    ebeyiebeleyemezsin: "§c§lBir ebeyi ebeleyemezsin!"
    #ebeyiebeleyemezsin yazısını düzenler
    cooldown_text: "§4Eşya özelliği hazır değil!"
    #cooldown mesajını düzenler.
    msg_color: " §e"
    #broadcast mesaj rengini düzenler.
    broadcast_text: "adlı kişiyi ebeledi."
    #broadcast mesajını düzenler. mesaj yazılma sırası: prefix + msgcolor + ebeleyenadı + ebelenen adı + broadcast_text
  effect:
    particle: "FIREWORKS_SPARK"
    #Default: FIREWORKS_SPARK
    particlepower: 150
    #Particle gücünü ayarlar. Default: 150
    sound: "ENTITY_DRAGON_FIREBALL_EXPLODE"
    #Default: ENTITY_FIREWORK_ROCKET_TWINKLE


mesaj: '&eÖldüğünüz için paranızın &6%%percent% (%money%$)''ı &egitti. Bir dahakine daha dikkatli ol!'
mesaj2: '&eRütbenizden dolayı paranız gitmedi.'

firstjoinmessages:
  messages:
    - "§7[§6Avalon§7] &6Büyük oyuncu &a%player%&6 bölüme ilk girişini yaptı! &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &a%player%&6, bölüme kayarak girdi. &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6Bir &a%player%,&6 belirdi. &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &a%player%&6 paraşütle bölüme iniş yaptı. &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6Hoşgeldin, &a%player%&6. Umarım pizza getirmişsindir. &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6Hoşgeldin, &a%player%&6. Seni bekliyorduk (^-^). &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &a%player%&6 bölüme giriş yaptı. Seems OP - please nerf. &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6&a%player%,&6 nerede? Sunucuda! &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6O bir kuş! O bir uçak! Hayır, o sadece bir &a%player%&6. &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &a%player% &6geldi, şimdi siz düşünün! &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &bZeus&6, &a%player% &6için şimşeklerini çakıyor! &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6Biz de gelene hoş geldin demek adettir. Hoş geldin &a%player%&6! &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6Yeni &3Lord&6 adayını selamlayın! İşte &a%player%&6! &cOyuncu Sırası: #%playersize%"
    - "§7[§6Avalon§7] &6İlk &3Kral&6 adayına hoşgeldin diyin. Selamlar &a%player%&6! &cOyuncu Sırası: #%playersize%"


sumobslist:
  - "Deniz İmparatoru"
  - "Suda Yürüyen"
  - "Kum Canavarı"
  - "Kil Canavarı"
  - "Su Gardiyanı"
  - "Su Cadısı"
  - "Su Okçusu"
  - "Derin Katil"
  - "Su Kedisi"
  - "Havuç Kral"
  - "Gümüş Balığı"
  - "Deniz Golemi"
  - "Su Kralı"
  - "Yeti"
  - "Buz Kurdu"
  - "Mürekkep Balığı"
  - "Donmuş Zombi"

runner:
  pistons:
    - "1191 38 -898"
    - "1190 38 -898"
    - "1189 38 -898"
    - "1188 38 -898"
    - "1187 38 -898"
    - "1186 38 -898"
    - "1185 38 -898"
    - "1184 38 -898"
    - "1183 38 -898"
    - "1182 38 -898"
    - "1181 38 -898"
    - "1180 38 -898"
    - "1179 38 -898"
    - "1178 38 -898"