name: AVALON
author:  _KatilCivciv_
description: Avalonun Omurilik Soğanı.
version: 1.3.4
api-version: 1.19
main: com.civciv.avalon.GrapplingHook
log_prefix: AVALON
soft-depend: [ProtocolLib,PlaceholderAPI,MythicMobs]
commands:
   givegrapplinghook:
       description: Oyuncuya kanca verir.
       usage: /<command>
       permission: op
   givehomingbow:
       description: gives a homing bow to the player
       usage: /<command>
       permission: op
   giveexplosivebow:
       description: gives a explosive bow to the player
       usage: /<command>
       permission: op
   giveaspickaxe:
       description: gives a AS pickaxe to the player
       usage: /<command>
       permission: op
   givetriplebow:
       description: gives a triple bow to the player
       usage: /<command>
       permission: op
   givetesthomingbow:
       description: Avalon Test Yayı I
       usage: /<command>
       permission: op
   givepersonalcompactor:
       description: oyuncuya Kişisel Sıkıştırıcı verir.
       usage: /<command>
       permission: op
   giveenchanteditems:
       description: oyuncuya büyülü eşya verir.
       usage: /<command>
       permission: op
   giveUndeadSword:
       description: oyuncuya UndeadSword verir.
       usage: /<command>
       permission: op
   giveTestUndeadSword:
       description: debug modu açık UndeadSword verir.
       usage: /<command>
       permission: op
   giveDragonKatili:
       description: Ejderha katili kılıcı verir.
       usage: /<command>
       permission: op
   giveTestDragonKatili:
     description: debug modu açık DragonKatili verir.
     usage: /<command>
     permission: op
   giveKubizmSword:
     description: Kübizm etkisine sahip kılıç verir.
     usage: /<command>
     permission: op
   giveTestKubizmSword:
     description: debug modu açık Kübizm kılıcı verir.
     usage: /<command>
     permission: op
   givesaklambactool:
     description: test eşyası
     usage: /<command>
     permission: op
   giveprismarinebow:
     description: test eşyası
     usage: /<command>
     permission: op
   ejderfix:
     description: ejderi portala geri çekme
     usage: /<command>
     permission: avalon.ejderfix